apiVersion: v1
kind: Service
metadata:
  name: kuber-test-demo
  labels:
    app: kuber-test-demo
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8010
      protocol: TCP
      name: https
  selector:
    app: kuber-test-demo
